### PR TITLE
Topic/lock file

### PR DESCRIPTION
**Pull request by danzelenak-usgs**

### CODE REVIEW

**Comment by danzelenak-usgs** [comment]
addressed peer review comments:
* added more detailed comment on using a lock
* removed dependency on zc.lockfile module in favor of the socket module
   * this allows us to avoid having to manually remove the lock or have a need for a close/remove_lock fn

**Comment by caustin-usgs** [comment]
just making sure that we dont need to add the cmd to remove the lock in the finally block

**Comment by danzelenak-usgs** [comment]
> just making sure that we dont need to add the cmd to remove the lock in the finally block

Yeah we should be fine with just the single removal after we make the call to place scenes in queue.  If the script throws an exception or exits for any reason, any socket objects will be garbage collected.

**Comment by caustin-usgs** [comment]
okay, looks good to me then

**Comment by danzelenak-usgs** [comment]
had just a quick fix to the release_lock function - was missing an argument to calling socket.shutdown()

**Pull request merged**
