### PR TITLE
ESPA 2.16.0

### PR DESCRIPTION
**Pull request by ronaldddilley**
Changes for the 2.16.0 release

### CODE REVIEW

**Comment by gschmidt-usgs** [comment]
Peer review complete.  All changes look good.

**Comment by gschmidt-usgs** [comment]
Change looks good.

**Comment by raydittmeier** [comment]
The changes look good.

**Comment by gschmidt-usgs** [comment]
Last change to support keeping the radsat band looks good.

**Comment by gschmidt-usgs** [comment]
The changes made for the cfmask business logic look appropriate.

**Comment by gschmidt-usgs** [comment]
The latest change looks valid based on the differences between LEDAPS and LaSRC.

**Pull request merged**
